import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Seo from "./ui/components/Seo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "coders monkey",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  title: string;
  description: string;
}

export default function RootLayout({
  children,
  title = metadata.title,
  description = metadata.description,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <Seo title={title} description={description} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
